import java.awt.HeadlessException;
import javax.swing.JOptionPane; 
import java.sql.Connection;
import java.sql.DriverManager; 
import java.sql.Statement; 
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JFrame;

public class Register extends javax.swing.JFrame {
    private String sql;

    /** Creates new form guest2 */
    public Register() {
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
        autoID();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        jPanel1 = new javax.swing.JPanel();
        tf1 = new javax.swing.JTextField();
        tf2 = new javax.swing.JTextField();
        tf4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        tf3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        p1 = new javax.swing.JPasswordField();
        p2 = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel2.setkEndColor(new java.awt.Color(109, 213, 250));
        kGradientPanel2.setkStartColor(new java.awt.Color(41, 128, 185));
        kGradientPanel2.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(41, 128, 185), 3, true));
        jPanel1.setLayout(null);

        tf1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tf1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(41, 128, 185)));
        tf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf1ActionPerformed(evt);
            }
        });
        jPanel1.add(tf1);
        tf1.setBounds(50, 230, 380, 25);

        tf2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tf2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(41, 128, 185)));
        jPanel1.add(tf2);
        tf2.setBounds(50, 310, 380, 25);

        tf4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tf4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(41, 128, 185)));
        tf4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf4ActionPerformed(evt);
            }
        });
        jPanel1.add(tf4);
        tf4.setBounds(50, 380, 380, 25);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(57, 250, 20));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Staff Id.");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-40, 200, 240, 20);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(57, 250, 20));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 270, 36, 20);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(57, 250, 20));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Phone");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(-30, 350, 210, 20);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(57, 250, 20));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Password");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(-50, 410, 260, 40);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(41, 128, 185));
        jLabel4.setText("Register Here");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 60, 490, 80);

        jButton1.setBackground(new java.awt.Color(41, 128, 185));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("ADD");
        jButton1.setToolTipText("Add New CustomerId");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 102), 3, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(140, 660, 200, 40);

        jButton3.setBackground(new java.awt.Color(41, 128, 185));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("SEARCH");
        jButton3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 102), 3, true));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(140, 720, 200, 40);

        jButton2.setBackground(new java.awt.Color(41, 128, 185));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("GO BACK");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 102), 3, true));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(140, 780, 200, 40);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(57, 250, 20));
        jLabel6.setText("Email");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(50, 560, 41, 16);

        tf3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tf3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(41, 128, 185)));
        tf3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf3ActionPerformed(evt);
            }
        });
        jPanel1.add(tf3);
        tf3.setBounds(50, 590, 390, 30);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(57, 250, 20));
        jLabel8.setText("Retype Password");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(50, 490, 130, 20);

        p1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        p1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(41, 128, 185)));
        jPanel1.add(p1);
        p1.setBounds(50, 520, 380, 25);

        p2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        p2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(41, 128, 185)));
        p2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p2ActionPerformed(evt);
            }
        });
        jPanel1.add(p2);
        p2.setBounds(50, 450, 380, 25);

        kGradientPanel2.add(jPanel1);
        jPanel1.setBounds(1090, 150, 500, 850);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\New folder\\logo3.PNG")); // NOI18N
        kGradientPanel2.add(jLabel5);
        jLabel5.setBounds(180, 320, 630, 640);

        label1.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        kGradientPanel2.add(label1);
        label1.setBounds(1600, 970, 470, 80);

        getContentPane().add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -100, 2380, 1170));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

public void autoID(){
try {
            Class.forName("java.sql.Driver");
            Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost/projectwork","root","1234");
            Statement stmt=(Statement)con.createStatement();
            String query="Select MAX(staffid) from reg;";
            ResultSet rs=stmt.executeQuery(query);
            rs.next();
            rs.getString("MAX(staffid)");
            if(rs.getString("MAX(staffid)")==null)
            {
              tf1.setText("S0001");
                
            }
            else
            {
             Long staffid=Long.parseLong(rs.getString("MAX(staffid)").substring(2,rs.getString("MAX(staffid)").length()));
             staffid++;
             tf1.setText("S0"+String.format("%03d",staffid));
            }
            
                      
        }
        catch (ClassNotFoundException e) 
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }                                        




    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           String pw =new String (p1.getPassword());
         String a=tf1.getText();
       String b=tf2.getText();
       String c=tf4.getText();
       String d=new String (p2.getPassword());
       String f=tf3.getText();
   
 if(c.length()>=10 && c.length()<=11) {   
     if(pw.equals(d)){
         
        
try{
    Class.forName("java.sql.Driver");
      Connection con=DriverManager.getConnection("jdbc:mysql://localhost/projectwork","root","1234");
    Statement stmt=con.createStatement();
           String query="insert into reg values('"+a+"','"+d+"','"+c+"','"+b+"','"+f+"',sysdate());";
   stmt.executeUpdate(query);
 
   JOptionPane.showMessageDialog(null,"Account has been created successfully");
    
}

catch (HeadlessException e)
{
    JOptionPane.showMessageDialog(null,e.getMessage());
}            catch (ClassNotFoundException e) {
    JOptionPane.showMessageDialog(null,e.getMessage());
             } catch (SQLException e) {
                 JOptionPane.showMessageDialog(null,e.getMessage());
             }
        tf4.setText("");
        p2.setText("");
        p1.setText("");
        tf1.setText("");
        tf2.setText("");
        tf3.setText("");
        
     }
     else{
     JOptionPane.showMessageDialog(null,"Password doesnt match");
     }
 }
 else{
     JOptionPane.showMessageDialog(null,"Please Enter Valid Phone Number");
 
 }
 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

       StaffLogin obj=new StaffLogin();
   obj.setVisible(true);
   this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
 String staffid=tf1.getText();
        try {
            Class.forName("java.sql.Driver");
            Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost/projectwork","root","1234");
            Statement stmt=(Statement)con.createStatement();
            String query="Select * from Reg where staffid='"+staffid+"';";
            ResultSet rs=stmt.executeQuery(query);
            if(rs.next())
            {
        String name = rs.getString("Name");
                
                String phone = rs.getString("PhnNo");
                
                String email=rs.getString("email");
                tf2.setText(" "+name);
                
                tf4.setText(" "+phone);
                
                tf3.setText(""+email);
            }    else
                    JOptionPane.showMessageDialog(null,"Invalid CustomerId");
            
        }
        catch (HeadlessException e) 
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        } catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null,e.getMessage());
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_formFocusGained

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        String timeStamp = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(Calendar.getInstance().getTime());
label1.setText(timeStamp);
    }//GEN-LAST:event_formWindowOpened

    private void tf4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf4ActionPerformed

    private void tf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf1ActionPerformed

    private void tf3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf3ActionPerformed

    private void p2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Register().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private javax.swing.JLabel label1;
    private javax.swing.JPasswordField p1;
    private javax.swing.JPasswordField p2;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf2;
    private javax.swing.JTextField tf3;
    private javax.swing.JTextField tf4;
    // End of variables declaration//GEN-END:variables
}
